name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - matplotlib
  - xarray
  - numpy
  - intake
  - cartopy
  - scikit-learn
  - pandas
  - intake-esm
  - aiohttp
  - s3fs
  - zarr
  - fsspec
  - xclim
  - pip
  - pip: 
    - pyclimdex
